# Generated by Django 4.0.3 on 2022-03-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enunciado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enunciados',
            name='direccion',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enunciados',
            name='imagen',
            field=models.TextField(default='null'),
        ),
    ]
